[phases.setup]
nixPkgs = ["nodejs_22", "chromium"]

[phases.install]
cmds = ["npm ci"]

[start]
cmd = "node src/api/scraper.api.js"

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "/nix/store/*-chromium-*/bin/chromium"
